CREATE DATABASE SGE;

CREATE TABLE TIPO_USUARIO(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DESCRICAO VARCHAR(13)
);


CREATE TABLE USUARIO(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SIAPE VARCHAR(10) UNIQUE NOT NULL,
	NOME VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	SENHA VARCHAR(20) NOT NULL,
	ID_TIPO_USUARIO INT,
	FOREIGN KEY(ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO(ID)
);


CREATE TABLE PESSOA(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TELEFONE VARCHAR(14),
	CAMPUS VARCHAR(20),
	REG_TRABALHO VARCHAR(4),
	AREA VARCHAR(20),
	CLASSE VARCHAR(10),
	DIRETORIA VARCHAR(20),
	SIAPEFK VARCHAR(10),
	FOREIGN KEY(SIAPEFK) REFERENCES USUARIO(SIAPE)
);



CREATE TABLE PLANO_TRABALHO(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ATIVIDADE_APOIO VARCHAR(200),
	ATIVIDADE_PESQUISA VARCHAR(200),
	ATIVIDADE_EXTENSAO VARCHAR(200),
	ID_PESSOA VARCHAR(10),
	FOREIGN KEY(ID_PESSOA) REFERENCES USUARIO(SIAPE)
);

CREATE TABLE ATIVIDADE_PEDAGOGICA(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ATIVIDADE VARCHAR(100),
	PORTARIA VARCHAR(10),
	ID_PLANO_TRABALHO INT,
	FOREIGN KEY(ID_PLANO_TRABALHO) REFERENCES PLANO_TRABALHO(ID)
);


CREATE TABLE ATIVIDADE_ENSINO(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DISCIPLINA VARCHAR(50) NOT NULL,
	CURSO VARCHAR(40) NOT NULL,
	CARGA_HORARIA INT NOT NULL,
	ID_PLANO_TRABALHO INT,
	FOREIGN KEY(ID_PLANO_TRABALHO) REFERENCES PLANO_TRABALHO(ID)

);

CREATE TABLE ENTREGA(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(15),
	SIAPE VARCHAR(7),
	SEMESTRE VARCHAR(10),
	DATAE DATE
);

INSERT INTO `TIPO_USUARIO`(`DESCRICAO`) VALUES ('ADMIN');
INSERT INTO `TIPO_USUARIO`(`DESCRICAO`) VALUES ('PROFESSOR');

INSERT INTO `USUARIO`(`SIAPE`, `NOME`, `EMAIL`, `SENHA`, `ID_TIPO_USUARIO`) VALUES ('00000','adm','adm@adm','00000', 1);
INSERT INTO `USUARIO`(`SIAPE`, `NOME`, `EMAIL`, `SENHA`, `ID_TIPO_USUARIO`) VALUES ('11111','prof','prof@prof','11111', 2);