CREATE DATABASE SGE;

CREATE TABLE TIPO_USUARIO(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DESCRICAO VARCHAR(13)
);


CREATE TABLE USUARIO(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SIAPE VARCHAR(10) UNIQUE NOT NULL,
	NOME VARCHAR(60) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(50) NOT NULL,
	ID_TIPO_USUARIO INT,
	FOREIGN KEY(ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO(ID)
);


CREATE TABLE PESSOA(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TELEFONE VARCHAR(100),
	CAMPUS VARCHAR(50),
	REG_TRABALHO VARCHAR(10),
	AREA VARCHAR(50),
	CLASSE VARCHAR(50),
	DIRETORIA VARCHAR(50),
	SIAPEFK VARCHAR(10),
	FOREIGN KEY(SIAPEFK) REFERENCES USUARIO(SIAPE)
);



CREATE TABLE PLANO_TRABALHO(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ATIVIDADE_APOIO VARCHAR(300),
	ATIVIDADE_PESQUISA VARCHAR(300),
	ATIVIDADE_EXTENSAO VARCHAR(300),
	ID_PESSOA VARCHAR(10),
	FOREIGN KEY(ID_PESSOA) REFERENCES USUARIO(SIAPE)
);

CREATE TABLE ATIVIDADE_PEDAGOGICA(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ATIVIDADE VARCHAR(200),
	PORTARIA VARCHAR(20),
	ID_PLANO_TRABALHO INT,
	FOREIGN KEY(ID_PLANO_TRABALHO) REFERENCES PLANO_TRABALHO(ID)
);


CREATE TABLE ATIVIDADE_ENSINO(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DISCIPLINA VARCHAR(100) NOT NULL,
	CURSO VARCHAR(100) NOT NULL,
	CARGA_HORARIA INT NOT NULL,
	ID_PLANO_TRABALHO INT,
	FOREIGN KEY(ID_PLANO_TRABALHO) REFERENCES PLANO_TRABALHO(ID)

);

CREATE TABLE ENTREGA(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(100),
	SIAPE VARCHAR(10),
	SEMESTRE VARCHAR(50),
	DATAE DATE
);

INSERT INTO `TIPO_USUARIO`(`DESCRICAO`) VALUES ('ADMIN');
INSERT INTO `TIPO_USUARIO`(`DESCRICAO`) VALUES ('PROFESSOR');

INSERT INTO `USUARIO`(`SIAPE`, `NOME`, `EMAIL`, `SENHA`, `ID_TIPO_USUARIO`) VALUES ('0','adm','adm@adm','0', 1);
INSERT INTO `USUARIO`(`SIAPE`, `NOME`, `EMAIL`, `SENHA`, `ID_TIPO_USUARIO`) VALUES ('1','prof','prof@prof','1', 2);