CREATE DATABASE SGE;

USE DATABASE SGE;

CREATE TABLE PESSOA(
SIAPE VARCHAR(10) PRIMARY KEY NOT NULL,
NOME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
TELEFONE VARCHAR(14),
CAMPUS VARCHAR(20),
REG_TRABALHO VARCHAR(4),
AREA VARCHAR(20),
CLASSE VARCHAR(10),
DIRETORIA VARCHAR(20)

);

CREATE TABLE TIPO_USUARIO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DESCRICAO VARCHAR(13)
);

CREATE TABLE USUARIO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
SENHA VARCHAR(100),
SIAPEFK VARCHAR(10),
ID_TIPO_USUARIO INT,
FOREIGN KEY(ID_TIPO_USUARIO) REFERENCES TIPO_USUARIO(ID),
FOREIGN KEY(SIAPEFK) REFERENCES PESSOA(SIAPE)
);

CREATE TABLE PLANO_TRABALHO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ATIVIDADE_APOIO VARCHAR(200),
ATIVIDADE_PESQUISA VARCHAR(200),
ATIVIDADE_EXTENSAO VARCHAR(200),
SIAPE_PESSOA VARCHAR(10),
FOREIGN KEY(SIAPE_PESSOA) REFERENCES PESSOA(SIAPE)
);

CREATE TABLE ATIVIDADE_ENSINO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DISCIPLINA VARCHAR(50),
CURSO VARCHAR(40),
CARGA_HORARIA INT,
ID_PLANO_TRABALHO INT,
FOREIGN KEY(ID_PLANO_TRABALHO) REFERENCES PLANO_TRABALHO(ID)
);

CREATE TABLE ATIVIDADE_PEDAGOGICA(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
ATIVIDADE VARCHAR(50),
PORTARIA VARCHAR(40),
ID_PLANO_TRABALHO INT,
FOREIGN KEY(ID_PLANO_TRABALHO) REFERENCES PLANO_TRABALHO(ID)
);

CREATE TABLE ENTREGA(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
DATAE DATE,
NOME VARCHAR(100),
SEMESTRE VARCHAR(50),
ID_PLANO_TRABALHO INT,
FOREIGN KEY(ID_PLANO_TRABALHO) REFERENCES PLANO_TRABALHO(ID)
);


INSERT INTO `TIPO_USUARIO`( `DESCRICAO`) VALUES ('ADMIN');
INSERT INTO `TIPO_USUARIO`( `DESCRICAO`) VALUES ('PROFESSOR');

INSERT INTO `PESSOA` (`SIAPE`, `NOME`, `EMAIL`, `TELEFONE`, `CAMPUS`, `REG_TRABALHO`, `AREA`, `CLASSE`, `DIRETORIA`) VALUES
('123', 'Admin', 'admin@jaboatao.ifpe.edu.br', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO `PESSOA` (`SIAPE`, `NOME`, `EMAIL`, `TELEFONE`, `CAMPUS`, `REG_TRABALHO`, `AREA`, `CLASSE`, `DIRETORIA`) VALUES ('321', 'nilson', 'nilson.junior@jaboatao.ifpe.edu.br', NULL, NULL, NULL, NULL, NULL, NULL);

INSERT INTO `USUARIO` (`SIAPEFK`, `SENHA`, `ID_TIPO_USUARIO`) VALUES ('123', '202cb962ac59075b964b07152d234b70', 1);
INSERT INTO `USUARIO` (`SIAPEFK`, `SENHA`, `ID_TIPO_USUARIO`) VALUES ('321', 'caf1a3dfb505ffed0d024130f58c5cfa', 2);