CREATE DATABASE SGE;


CREATE TABLE ADMINISTRADOR(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(50),
	SIAPE VARCHAR(10),
	SENHA VARCHAR(8)

);

CREATE TABLE PROFESSOR(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOME VARCHAR(50) NOT NULL,
	SIAPE VARCHAR(10) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	SENHA VARCHAR(20) NOT NULL,
	TELEFONE VARCHAR(14),
	CAMPUS VARCHAR(20),
	REG_TRABALHO VARCHAR(4),
	AREA VARCHAR(20),
	CLASSE VARCHAR(10),
	DIRETORIA VARCHAR(20)

);

CREATE TABLE PLANO_TRABALHO(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ATIVIDADE_APOIO VARCHAR(200),
	ATIVIDADE_PESQUISA VARCHAR(200),
	ATIVIDADE_EXTENSAO VARCHAR(200),

	ID_PROFESSOR INT,
	FOREIGN KEY(ID_PROFESSOR) REFERENCES PROFESSOR(ID)

);

CREATE TABLE ATIVIDADE_PEDAGOGICA(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ATIVIDADE VARCHAR(100),
	PORTARIA VARCHAR(10),
	ID_PLANO_TRABALHO INT,
	FOREIGN KEY(ID_PLANO_TRABALHO) REFERENCES PLANO_TRABALHO(ID)
	
);


CREATE TABLE ATIVIDADE_ENSINO(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DISCIPLINA VARCHAR(50) NOT NULL,
	CURSO VARCHAR(40) NOT NULL,
	CARGA_HORARIA INT NOT NULL,
	ID_PLANO_TRABALHO INT,
	FOREIGN KEY(ID_PLANO_TRABALHO) REFERENCES PLANO_TRABALHO(ID)

);

CREATE TABLE REGISTRO_ENTREGA(

	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	DATA_ENTREGA DATE,
	ID_ADMIN INT,
	ID_PLANO_TRABALHO INT,
	FOREIGN KEY(ID_ADMIN) REFERENCES ADMINISTRADOR(ID),
	FOREIGN KEY(ID_PLANO_TRABALHO) REFERENCES PLANO_TRABALHO(ID)

);

CREATE TABLE ENTREGA(
	
	ID INT AUTO_INCREMENT PRIMARY KEY,
	NOME varchar(40) NOT NULL,
	SIAPE VARCHAR(10) NOT NULL,
	SEMESTRE VARCHAR(10) NOT NULL,
	DATAE date NOT NULL
);

CREATE TABLE PERFIL(
	
	ID INT AUTO_INCREMENT PRIMARY KEY,
	DESCRICAO VARCHAR(20)
);

CREATE TABLE TELA( 

	ID INT AUTO_INCREMENT PRIMARY KEY,
	DESCRICAO_FUNCAO VARCHAR(50) NOT NULL,
	URL VARCHAR (40)
);

CREATE TABLE USUARIO(

	ID INT AUTO_INCREMENT PRIMARY KEY,
	SIAPE VARCHAR(10) NOT NULL,
	ID_PERFIL INT,
	FOREIGN KEY(ID_PERFIL) REFERENCES PERFIL(ID)
);